INSERT INTO characters (name) VALUES ("Diala Passil");
INSERT INTO characters (name) VALUES ("Fenn Signis");
INSERT INTO characters (name) VALUES ("Gaarkhan");
INSERT INTO characters (name) VALUES ("Gideon Argus");
INSERT INTO characters (name) VALUES ("Jyn Odan");
INSERT INTO characters (name) VALUES ("Mak Eshka'rey");
INSERT INTO characters (name) VALUES ("Empire");
INSERT INTO cards (name, type) VALUES ("Diala Passil", "Deployment");
INSERT INTO cards (name, type) VALUES ("Fenn Signis", "Deployment");
INSERT INTO cards (name, type) VALUES ("Gaarkhan", "Deployment");
INSERT INTO cards (name, type) VALUES ("Gideon Argus", "Deployment");
INSERT INTO cards (name, type) VALUES ("Jyn Odan", "Deployment");
INSERT INTO cards (name, type) VALUES ("Mak Eshka'rey", "Deployment");
INSERT INTO cards (name, type) VALUES ("Luke Skywalker (Hero of the Rebellion)", "Deployment");
INSERT INTO cards (name, type) VALUES ("Rebel Trooper", "Deployment");
INSERT INTO cards (name, type) VALUES ("Rebel Saboteur", "Deployment");
INSERT INTO cards (name, type) VALUES ("Rebel High Command", "Deployment");
INSERT INTO cards (name, type) VALUES ("Balance of the Force", "Deployment");
INSERT INTO cards (name, type) VALUES ("Chewbacca", "Deployment");
INSERT INTO cards (name, type) VALUES ("Han Solo", "Deployment");
INSERT INTO cards (name, type, empire) VALUES ("Stormtrooper", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Stormtrooper (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Imperial Officer", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Imperial Officer (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("E-Web Engineer", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("E-Web Engineer (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Royal Guard", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Royal Guard (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Probe Droid", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Probe Droid (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("AT-ST", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Darth Vader (Lord of the Sith)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("General Weiss (Field Commander)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Royal Guard Champion", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Temporary Alliance (Imperial)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Trandoshan Hunter", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Trandoshan Hunter (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Nexu", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Nexu (Elite)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("IG-88 (Assassin Droid)", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Devious Scheme", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("First Strike", "Deployment", true);
INSERT INTO cards (name, type, empire) VALUES ("Temporary Alliance (Mercenary)", "Deployment", true);
INSERT INTO cards (name, type) VALUES ("Pummel", "Command");
INSERT INTO cards (name, type) VALUES ("Marksman", "Command");
INSERT INTO cards (name, type) VALUES ("Sit Tight", "Command");
INSERT INTO cards (name, type) VALUES ("Expose Weakness", "Command");
INSERT INTO cards (name, type) VALUES ("Recovery", "Command");
INSERT INTO cards (name, type) VALUES ("Take Initiative", "Command");
INSERT INTO cards (name, type) VALUES ("Rally", "Command");
INSERT INTO cards (name, type) VALUES ("To The Limit", "Command");
INSERT INTO cards (name, type) VALUES ("Fleet Footed", "Command");
INSERT INTO cards (name, type) VALUES ("Take Cover", "Command");
INSERT INTO cards (name, type) VALUES ("Deadeye", "Command");
INSERT INTO cards (name, type) VALUES ("Celebration", "Command");
INSERT INTO cards (name, type) VALUES ("Urgency", "Command");
INSERT INTO cards (name, type) VALUES ("Element of Surprise", "Command");
INSERT INTO cards (name, type) VALUES ("Planning", "Command");
INSERT INTO cards (name, type) VALUES ("Covering Fire", "Command");
INSERT INTO cards (name, type) VALUES ("Hunter Protocol", "Command");
INSERT INTO cards (name, type) VALUES ("Maximum Firepower", "Command");
INSERT INTO cards (name, type) VALUES ("Guardian Stance", "Command");
INSERT INTO cards (name, type) VALUES ("Ferocity", "Command");
INSERT INTO cards (name, type) VALUES ("Price on Their Heads", "Command");
INSERT INTO cards (name, type) VALUES ("Take it Down", "Command");
INSERT INTO cards (name, type) VALUES ("Burst Fire", "Command");
INSERT INTO cards (name, type) VALUES ("One in a Million", "Command");
INSERT INTO cards (name, type) VALUES ("Sarlacc Sweep", "Command");
INSERT INTO cards (name, type) VALUES ("Furious Charge", "Command");
INSERT INTO cards (name, type) VALUES ("Shadow Ops", "Command");
INSERT INTO cards (name, type) VALUES ("Deflection", "Command");
INSERT INTO cards (name, type) VALUES ("Telekinetic Throw", "Command");
INSERT INTO cards (name, type) VALUES ("Meditation", "Command");
INSERT INTO cards (name, type) VALUES ("Knowledge and Defense", "Command");
INSERT INTO cards (name, type) VALUES ("Son of Skywalker", "Command");
INSERT INTO cards (name, type) VALUES ("Regroup", "Command");
INSERT INTO cards (name, type) VALUES ("Lure of the Dark Side", "Command");
INSERT INTO cards (name, type) VALUES ("Lord of the Sith", "Command");
INSERT INTO cards (name, type) VALUES ("Close the Gap", "Command");
INSERT INTO cards (name, type) VALUES ("Force Lightning", "Command");
INSERT INTO cards (name, type) VALUES ("A New Threat", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Under Siege", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Imperial Hospitality", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Fly Solo", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Incoming", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Drawn In", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Chain of Command", "Story Mission");
INSERT INTO cards (name, type) VALUES ("The Source", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Last Stand", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Desperate Hour", "Story Mission");
INSERT INTO cards (name, type) VALUES ("Brushfire", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Temptation", "Side Mission");
INSERT INTO cards (name, type) VALUES ("High Moon", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Indebted", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Loose Cannon", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Friends of Old", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Sorry About the Mess", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Homecoming", "Side Mission");
INSERT INTO cards (name, type) VALUES ("The Spice Job", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Target of Opportunity", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Viper's Den", "Side Mission");
INSERT INTO cards (name, type) VALUES ("A Simple Task", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Generous Donations", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Luxury Cruise", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Sympathy for the Rebellion", "Side Mission");
INSERT INTO cards (name, type) VALUES ("Heroic", "Reward");
INSERT INTO cards (name, type) VALUES ("Legendary", "Reward");
INSERT INTO cards (name, type) VALUES ("The Ways of the Force", "Reward");
INSERT INTO cards (name, type, deck) VALUES ("Veteran Prowess", "Reward", "Fenn Signis");
INSERT INTO cards (name, type, deck) VALUES ("Peacemaker", "Reward", "Jyn Odan");
INSERT INTO cards (name, type, deck) VALUES ("Shu Yen's Lightsaber", "Reward", "Diala Passil");
INSERT INTO cards (name, type, deck) VALUES ("Life Debt", "Reward", "Gaarkhan");
INSERT INTO cards (name, type, deck) VALUES ("Fearless Leader", "Reward", "Gideon Argus");
INSERT INTO cards (name, type, deck) VALUES ("Shadow Suit", "Reward", "Mak Eshka'rey");
INSERT INTO cards (name, type) VALUES ("Allied Operations", "Reward");
INSERT INTO cards (name, type) VALUES ("Rebel Recon", "Reward");
INSERT INTO cards (name, type) VALUES ("Adrenal Implant", "Reward");
INSERT INTO cards (name, type, empire) VALUES ("Old Wounds", "Reward", true);
INSERT INTO cards (name, type, empire) VALUES ("Special Operations", "Reward", true);
INSERT INTO cards (name, type, empire) VALUES ("Supply Deficit", "Reward", true);
INSERT INTO cards (name, type, empire) VALUES ("Imperial Industry (Reward Card)", "Reward", true);
INSERT INTO cards (name, type, tier, cost) VALUES ("DH-17", "item", 1, 200);
INSERT INTO cards (name, type, tier, cost) VALUES ("E-11", "item", 1, 400);
INSERT INTO cards (name, type, tier, cost) VALUES ("DL-44", "item", 1, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("Vibroblade", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Armored Gauntlets", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Balanced Hilt", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Extended Haft", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Tactical Display", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Marksman Barrel", "item", 1, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Combat Coat", "item", 1, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("Survival Gear", "item", 1, 250);
INSERT INTO cards (name, type, tier, cost) VALUES ("Portable Medkit", "item", 1, 450);
INSERT INTO cards (name, type, tier, cost) VALUES ("Combat Coat", "item", 2, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("A280", "item", 2, 600);
INSERT INTO cards (name, type, tier, cost) VALUES ("T-21", "item", 2, 900);
INSERT INTO cards (name, type, tier, cost) VALUES ("434 'Deathhammer'", "item", 2, 600);
INSERT INTO cards (name, type, tier, cost) VALUES ("Vibro Knucklers", "item", 2, 400);
INSERT INTO cards (name, type, tier, cost) VALUES ("BD-1 Vibro-Ax", "item", 2, 600);
INSERT INTO cards (name, type, tier, cost) VALUES ("High-Impact Guard", "item", 2, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("Spread Barrel", "item", 2, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Overcharger", "item", 2, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Laminate Armor", "item", 2, 700);
INSERT INTO cards (name, type, tier, cost) VALUES ("Extra Ammunition", "item", 2, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Slicing Tools", "item", 2, 250);
INSERT INTO cards (name, type, tier, cost) VALUES ("Pulse Cannon", "item", 3, 1200);
INSERT INTO cards (name, type, tier, cost) VALUES ("DXR-6", "item", 3, 1000);
INSERT INTO cards (name, type, tier, cost) VALUES ("Sporting Blaster", "item", 3, 900);
INSERT INTO cards (name, type, tier, cost) VALUES ("Force Pike", "item", 3, 1100);
INSERT INTO cards (name, type, tier, cost) VALUES ("Laminate Armor", "item", 3, 700);
INSERT INTO cards (name, type, tier, cost) VALUES ("Personal Shields", "item", 3, 550);
INSERT INTO cards (name, type, tier, cost) VALUES ("Reinforced Helmet", "item", 3, 300);
INSERT INTO cards (name, type, tier, cost) VALUES ("Combat Visor", "item", 3, 350);
INSERT INTO cards (name, type, tier, cost) VALUES ("Combat Knife", "item", 3, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("Shock Emitter", "item", 3, 500);
INSERT INTO cards (name, type, tier, cost) VALUES ("Disruption Cell", "item", 3, 600);
INSERT INTO cards (name, type, tier, cost) VALUES ("Telescoping Sights", "item", 3, 400);
INSERT INTO cards (name, type) VALUES ("Shock Grenade", "supply");
INSERT INTO cards (name, type) VALUES ("Adrenal Stim", "supply");
INSERT INTO cards (name, type) VALUES ("Emergency Medpac", "supply");
INSERT INTO cards (name, type) VALUES ("Bacta Infusion", "supply");
INSERT INTO cards (name, type) VALUES ("Valuable Goods", "supply");
INSERT INTO cards (name, type) VALUES ("C22 Frag Grenade", "supply");
INSERT INTO cards (name, type) VALUES ("Troop Data", "supply");
INSERT INTO cards (name, type) VALUES ("C1 Comlink", "supply");
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Show of Force", 0, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Combat Medic", 1, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Riot Grenades", 1, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Assault Armor", 2, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Endless Ranks", 2, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Shock Troopers", 3, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Sustained Fire", 3, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Combat Veterans", 4, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Shock and Awe", 4, "class", "Military Might", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Experimental Arms", 0, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Jetpacks", 1, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Technical Support", 1, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Failsafe", 2, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Hidden Detonators", 2, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Cloaking Device", 3, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Arc Blasters", 3, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Superior Augments", 4, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Adaptive Weapons", 4, "class", "Technological Superiority", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Prey Upon Doubt", 0, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Savage Weaponry", 1, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Surgical Strike", 1, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Heavy Pressure", 2, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Exploit Weakness", 2, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Executioner", 3, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Weary Target", 3, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("Oppression", 4, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck, empire) VALUES ("No Quarter", 4, "class", "Subversive Tactics", true);
INSERT INTO cards (name, cost, type, deck) VALUES ("Plasteel Staff", 0, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Force Adept", 1, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Force Throw", 1, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Battle Meditation", 2, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Defensive Stance", 2, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Art of Movement", 3, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Snap Kick", 3, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Dancing Weapon", 4, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Way of the Sarlacc", 4, "class", "Diala Passil");
INSERT INTO cards (name, cost, type, deck) VALUES ("Infantry Rifle", 0, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Tactical Movement", 1, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Take Cover (Fenn)", 1, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Adrenaline Rush", 2, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Weapon Expert", 2, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Suppressive Fire", 3, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Trench Fighter", 3, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Rebel Elite", 4, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Superior Positioning", 4, "class", "Fenn Signis");
INSERT INTO cards (name, cost, type, deck) VALUES ("Vibro-Ax", 0, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Wookiee Fortitude", 1, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Wookiee Loyalty", 1, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Ferocity (Gaarkhan)", 2, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Staggering Blow", 2, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Vicious Strike", 3, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Rampage", 3, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Unstoppable", 4, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Brutal Cleave", 4, "class", "Gaarkhan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Holdout Blaster", 0, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Called Shot", 1, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Military Efficiency", 1, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Air of Command", 2, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Mobile Tactician", 2, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("For the Cause!", 3, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Rallying Shout", 3, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Hammer and Anvil", 4, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Master Stroke", 4, "class", "Gideon Argus");
INSERT INTO cards (name, cost, type, deck) VALUES ("Vintage Blaster", 0, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Quick as a Whip", 1, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Smuggler's Luck", 1, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Cheap Shot", 2, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Roll with It", 2, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Get Cocky", 3, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Gunslinger", 3, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Sidewinder", 4, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Trick Shot", 4, "class", "Jyn Odan");
INSERT INTO cards (name, cost, type, deck) VALUES ("Longblaster", 0, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Disengage", 1, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Supply Network", 1, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Jeswandi Training", 2, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Target Acquired", 2, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Execute", 3, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Expertise", 3, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("Decoy", 4, "class", "Mak Eshka'rey");
INSERT INTO cards (name, cost, type, deck) VALUES ("No Escape", 4, "class", "Mak Eshka'rey");