// Pull in required dependencies
var path = require('path');
var multer = require('multer'),
	bodyParser = require('body-parser'),
	path = require('path');
var fs = require('fs');


// Import the list of friend entries

// Export API routes
module.exports = function (app) {
	//all friends -- read in --- asynch
	//no problems because it will send to browser
	//line by line as it comes in
	// app.get('/picture/create', function (req, response) {
	// 	console.log("hit the create inside of api routes")
	// });

	app.post('/picture/create', multer({ dest: './app/public/uploads/' }).single('upl'), function (req, res) {
		console.log('did a post inside of api routes');
		console.log(req.file);
		if (!req.file) {
			console.log("No file received");
			return res.send({
				success: false
			});

		} else {
			console.log('file received');
			return res.send({
				success: true
			})
		}
	});


	//this is the routine for pulling images	
	app.post('/picture/create-img2', multer({ dest: './app/public/uploads/' }).single('upl'), function (req, res) {
		console.log('did a post inside of api routes');
		console.log(req.file);
		if (!req.file) {
			console.log("No file received");
			return res.send({
				success: false
			});

		} else {
			console.log('file received');
			return res.send({
				success: true
			})
		}
	});

	var upload = multer({ dest: __dirname + '/public/uploads/' });
	var type = upload.single('upl');

	var uploadFile = __dirname;
	var newLen = uploadFile.length - 7;
	uploadFile = uploadFile.substr(0, newLen) + '/public/uploads/' + "test1.png";
	//var uploadFile = '../public/uploads/' + "test1.png";
	console.log(uploadFile);

	app.post('/picture/create-img2', type, function (req, res) {
		console.log("\n\n from upload");

		//console.log( Object.keys(req.body)[0]);
		var tempStr = "" + Object.keys(req.body)[0];
		var tempStr_1 = tempStr.substr(0, 40);
		var base64Data = tempStr.replace(/^data:image\/png;base64,/, "");
		var dataIn = tempStr.replace(/^data:image\/png;base64,/, "");
		var tempStr_2 = base64Data.substr(0, 40);
		console.log(tempStr_1 + "-and-" + tempStr_2);

		//var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(dataIn, 'base64');
		fs.writeFile(uploadFile, buf);


		/*
		//console.log(req.body);
		fs.writeFile(uploadFile, base64Data, 'base64', function (err) {
			if (err) {
				//can't error, because problem is with log file !!!
				console.log('error with log file.  error=' + err);
				throw err;
			} else {
				console.log('saved successfully');
			};

		

			//console.log(req.file);
			// do stuff with file
		});
		*/

	});

	app.post('/picture/create-img', type, function (req, res) {

		var fs = require('fs');
		// string generated by canvas.toDataURL()
		var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
			+ "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
			+ "3gAAAABJRU5ErkJggg==";
		// Grab the extension to resolve any image error
		var ext = img.split(';')[0].match(/jpeg|png|gif/)[0];
		// strip off the data: url prefix to get just the base64-encoded bytes
		var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(img, 'base64');

		var uploadFile = __dirname;
		var newLen = uploadFile.length - 7;
		uploadFile = uploadFile.substr(0, newLen) + '/public/uploads/' + "test2.png";
			fs.writeFile( uploadFile, buf);
//			fs.writeFile('image.' + ext, buf);
	});


};

// //for storage of pictures
// import bodyParser from 'body-parser';
// import morgan from 'morgan';
// import express from 'express';
// const app2 = express();
// app2.use(bodyParser.json());
// app2.use(bodyParser.urlencoded({extended: true}));
// app2.use(morgan('dev'));


// //this is the picture_controller.js file
// //really /picture
// router.get('/', function(req,res) {
//   res.render('../app/views/camera');
// });

// router.post('/create', upload.single('avatar'),  function(req, res) {
//   console.log("hit the picture create route");
//   const storage = multer.diskStorage({
//     destination: '/public/uploads',
//     filename: function (req, file, callback) {
//       //..
//     }
//   });


// });
